# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\zhy02\Desktop\urp\ui\loginUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(968, 629)
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 351, 521))
        self.frame.setStyleSheet("#frame{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(32, 28, 145, 255), stop:0.505682 rgba(57, 175, 210, 255), stop:1 rgba(55, 239, 235, 255));\n"
"    \n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 130, 281, 51))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(350, 0, 351, 521))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 351, 401))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_3)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 351, 391))
        self.stackedWidget.setStyleSheet("QLineEdit{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    broder:nono;\n"
"    broder-bottom:1px solid block;\n"
"}\n"
"\n"
"QPushBottom{\n"
"    background-color: rgba(0, 0, 0);\n"
"    broder-bottom:1px solid block;\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.loginF = QtWidgets.QWidget()
        self.loginF.setObjectName("loginF")
        self.LButton = QtWidgets.QPushButton(self.loginF)
        self.LButton.setGeometry(QtCore.QRect(60, 290, 231, 31))
        self.LButton.setObjectName("LButton")
        self.Laccont = QtWidgets.QLineEdit(self.loginF)
        self.Laccont.setGeometry(QtCore.QRect(10, 120, 331, 41))
        self.Laccont.setObjectName("Laccont")
        self.Lpassword = QtWidgets.QLineEdit(self.loginF)
        self.Lpassword.setGeometry(QtCore.QRect(10, 190, 331, 41))
        self.Lpassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Lpassword.setObjectName("Lpassword")
        self.stackedWidget.addWidget(self.loginF)
        self.register_2 = QtWidgets.QWidget()
        self.register_2.setObjectName("register_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.register_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(20, 60, 311, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.register_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(20, 100, 311, 31))
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.register_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(20, 140, 111, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.register_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(20, 180, 311, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.register_2)
        self.lineEdit_7.setGeometry(QtCore.QRect(140, 140, 91, 31))
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.register_2)
        self.lineEdit_8.setGeometry(QtCore.QRect(20, 220, 311, 31))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.pushButton_5 = QtWidgets.QPushButton(self.register_2)
        self.pushButton_5.setGeometry(QtCore.QRect(40, 320, 261, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.comboBox = QtWidgets.QComboBox(self.register_2)
        self.comboBox.setGeometry(QtCore.QRect(240, 140, 91, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.register_2)
        self.lineEdit_9.setGeometry(QtCore.QRect(20, 260, 311, 31))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.stackedWidget.addWidget(self.register_2)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(0, 400, 351, 81))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setGeometry(QtCore.QRect(0, -10, 351, 51))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.splitter = QtWidgets.QSplitter(self.frame_5)
        self.splitter.setGeometry(QtCore.QRect(10, 10, 331, 28))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.pushButton = QtWidgets.QPushButton(self.splitter)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.splitter)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.splitter)
        self.pushButton_3.setObjectName("pushButton_3")
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.pushButton_3.clicked.connect(LoginWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "MainWindow"))
        self.label.setText(_translate("LoginWindow", "水产养殖智能管控系统"))
        self.LButton.setText(_translate("LoginWindow", "确认"))
        self.Laccont.setPlaceholderText(_translate("LoginWindow", "账号"))
        self.Lpassword.setPlaceholderText(_translate("LoginWindow", "密码"))
        self.lineEdit_3.setPlaceholderText(_translate("LoginWindow", "账号"))
        self.lineEdit_4.setPlaceholderText(_translate("LoginWindow", "密码"))
        self.lineEdit_5.setPlaceholderText(_translate("LoginWindow", "姓名"))
        self.lineEdit_6.setPlaceholderText(_translate("LoginWindow", "账号"))
        self.lineEdit_7.setPlaceholderText(_translate("LoginWindow", "年龄"))
        self.lineEdit_8.setPlaceholderText(_translate("LoginWindow", "密码"))
        self.pushButton_5.setText(_translate("LoginWindow", "确认注册"))
        self.comboBox.setItemText(0, _translate("LoginWindow", "性别"))
        self.comboBox.setItemText(1, _translate("LoginWindow", "男"))
        self.comboBox.setItemText(2, _translate("LoginWindow", "女"))
        self.lineEdit_9.setPlaceholderText(_translate("LoginWindow", "确认密码"))
        self.pushButton.setText(_translate("LoginWindow", "登录"))
        self.pushButton_2.setText(_translate("LoginWindow", "注册"))
        self.pushButton_3.setText(_translate("LoginWindow", "退出"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginWindow = QtWidgets.QMainWindow()
    ui = Ui_LoginWindow()
    ui.setupUi(LoginWindow)
    LoginWindow.show()
    sys.exit(app.exec_())
